### ISSUE TITLE
Remove --no-ri and --no-rdoc uses

### ISSUE THREAD

**Issue by paulasaurus** [engineyard/engineyard-serverside#185]
Rubygems 3.x no longer supports the use of `--no-ri` and `--no-rdoc` with `gem install`. Instead `--no-document` should be used instead. 

We need usages of `--no-ri` and `--no-rdoc` to be updated in order to make serverside Rubygems 3.x compatible.

Rubygems 3.x will be packaged with Ruby 2.6, which will be offered on v6 and v5. AFAIK `--no-document` has been supported for many years, so it may be the case that all stacks will support it, otherwise we need to splinter serverside into stable-v1/2/4 and v5/6 versions.

**Comment by ess** [comment]
Interestingly, there are only two places where we use the problematic flags explicitly:

* When installing bundler
* When propagating engineyard-serverside to all applicable instances in the environment

That being the case, this should be a relatively easy change. Rather than splitting between older stacks and newer stacks, I'd *much* prefer that we just detect if gem-3.x.y is in use, specifying the flags based on that calculation.

**Comment by ess** [comment]
Hey @remotedevops  ... assigned this to you for implementation. Give a yell if you need a hand.

**Comment by remotedevops** [comment]
I removed `--no-ri --no-rdoc` from serverside when installing bundler. https://github.com/engineyard/engineyard-serverside/pull/186

On the chef recipes, I'll add `--no-ri --no-rdoc --no-document` to /root/.gemrc. https://github.com/engineyard/ey-cookbooks-stable-v5/tree/add-no-document

> When propagating engineyard-serverside to all applicable instances in the environment

This uses `/usr/local/ey_resin/bin/gem` which is separate from the system `gem`. We can leave `--no-ri --no-rdoc` and it won't cause issues with rubygems 3.0.3 on the system. I've tested this on v5.

**Comment by ess** [comment]
Resolved by #186
